### ISSUE TITLE
Use BigDecimal in DoubleValueCollector

### ISSUE THREAD

**Issue by fnobilia** [RADAR-CNS/RADAR-Backend#22]
In `org.radarcns.stream.collector.DoubleValueCollector` convert
- min
- max
- count
- avg
- quartile
- iqr

to `BigDecimal`. In this way according to needs, we can extract values in the most suitable format using

- `BigDecimal#doubleValue()`
- `BigDecimal#floatValue()`
- `BigDecimal#intValue()`
- `BigDecimal#longValue()`

**Comment by blootsvoets** [comment]
Note that for `avg`, when using BigDecimal, we have to actively choose the precision we want. BigDecimal works with a fixed precision, and with division with infinite symbols, it will throw an ArithmeticException. From [BigDecimal javadoc](https://docs.oracle.com/javase/7/docs/api/java/math/BigDecimal.html):

> When a MathContext object is supplied with a precision setting of 0 (for example, MathContext.UNLIMITED), arithmetic operations are exact, as are the arithmetic methods which take no MathContext object. (This is the only behavior that was supported in releases prior to 5.) As a corollary of computing the exact result, the rounding mode setting of a MathContext object with a precision setting of 0 is not used and thus irrelevant. In the case of divide, the exact quotient could have an infinitely long decimal expansion; for example, 1 divided by 3. If the quotient has a nonterminating decimal expansion and the operation is specified to return an exact result, an ArithmeticException is thrown. Otherwise, the exact result of the division is returned, as done for other operations.

How would we choose the number of decimals here? The advantage of double is that it adjusts the amount of decimals automatically (plus it uses a binary representation/2-exponent instead of a decimal representation/10-exponent).

**Comment by fnobilia** [comment]
Can we directly specify `DECIMAL128` while instanceting?
From [MathContext](https://docs.oracle.com/javase/7/docs/api/java/math/MathContext.html)

> static MathContext	DECIMAL128
> A MathContext object with a precision setting matching the IEEE 754R Decimal128 format, 34 digits, and a rounding mode of HALF_EVEN, the IEEE 754R default.

Something like
```java
BigDecimal min = new BigDecimal(Double.MAX_VALUE, MathContext.DECIMAL128);
```

So far `collectors` are used to computed data shown through dashboard, `DECIMAL128` could be enough. If this precision is ok for us we can double check with WP8 and front-end team.

**Comment by blootsvoets** [comment]
No longer part of this repo, won't fix.
